Repository SophT-Team/SophT, pull requests merged in 2022-12, with the labels that each got.

#81 (#74) feat: add mypy static type checking
  Makefile
  examples/2d_examples/ImmersedFlexiblePendulumCases/immersed_flexible_pendulum_with_rigid_cylinder.py
  examples/2d_examples/LidDrivenCavityCase/lid_driven_cavity_grid.py
  examples/2d_examples/OctopusArmCase/arm_functions_2d.py
  examples/2d_examples/OctopusArmCase/run_coupling_tapered_arm_and_cylinder.py
  examples/2d_examples/OctopusArmCase/set_environment_tapered_arm_cylinder.py
  examples/3d_examples/OctopusArmCase3D/arm_functions_3d.py
  examples/3d_examples/OctopusArmCase3D/run_tapered_arm_and_sphere_with_flow.py
  examples/3d_examples/OctopusArmCase3D/set_environment_tapered_arm_and_sphere_with_flow.py
  poetry.lock
  pyproject.toml
  sopht/numeric/eulerian_grid_ops/stencil_ops_3d/laplacian_filter_3d.py
  sopht/simulator/immersed_body/cosserat_rod/cosserat_rod_flow_interaction.py
  sopht/simulator/immersed_body/cosserat_rod/cosserat_rod_forcing_grids.py
  sopht/simulator/immersed_body/flow_forces.py
  sopht/simulator/immersed_body/immersed_body_flow_interaction.py
  sopht/simulator/immersed_body/rigid_body/rigid_body_flow_interaction.py
  sopht/simulator/immersed_body/rigid_body/rigid_body_forcing_grids.py
  sopht/utils/io.py
  sopht/utils/rod_viz.py
Labels: enhancement, prio:medium

#86 fix: nearest grid supporrt rounding error
  sopht/numeric/immersed_boundary_ops/EulerianLagrangianGridCommunicator2D.py
  sopht/numeric/immersed_boundary_ops/EulerianLagrangianGridCommunicator3D.py
Labels: invalid, prio:high

#87 (#84) flow simulator internal time update
  examples/2d_examples/FlowPastCylinderCase/flow_past_cylinder.py
  examples/2d_examples/FlowPastRodCase/flow_past_rod.py
  examples/2d_examples/ImmersedContinuumSnakeCase/immersed_continuum_snake.py
  examples/2d_examples/ImmersedFlexiblePendulumCases/immersed_flexible_pendulum_with_rigid_cylinder.py
  examples/2d_examples/LambOseenVortexCase/lamb_oseen_vortex.py
  examples/2d_examples/LidDrivenCavityCase/lid_driven_cavity_case.py
  examples/2d_examples/OctopusArmCase/run_coupling_tapered_arm_and_cylinder.py
  examples/2d_examples/VortexInducedFlagFlappingCase/turek_and_hron_benchmark.py
  examples/3d_examples/ElasticNetCase/immersed_elastic_net.py
  examples/3d_examples/FlowPastRodCase/flow_past_rod_case.py
  examples/3d_examples/FlowPastSphereCase/flow_past_sphere_case.py
  examples/3d_examples/FlowThroughPipeCase/flow_through_circular_pipe_case.py
  examples/3d_examples/MagneticCiliaCarpetCase/immersed_magnetic_cilia_carpet.py
  examples/3d_examples/OctopusArmCase3D/run_tapered_arm_and_sphere_with_flow.py
  examples/3d_examples/PointSourceAdvectAndDiffuseCase/point_source_advection_diffusion.py
  sopht/simulator/flow/flow_simulators_2d.py
  sopht/simulator/flow/flow_simulators_3d.py
  tests/test_simulator/test_flow/test_flow_simulators_2d.py
Labels: prio:high, refactor

#95 (#92) refactor: remove advection stretching split from flow simulator 3d
  examples/3d_examples/ElasticNetCase/immersed_elastic_net.py
  examples/3d_examples/FlowPastRodCase/flow_past_rod_case.py
  examples/3d_examples/FlowPastSphereCase/flow_past_sphere_case.py
  examples/3d_examples/HillSphericalVortexCase/hill_sphere_vortex_case.py
  examples/3d_examples/MagneticCiliaCarpetCase/immersed_magnetic_cilia_carpet.py
  examples/3d_examples/OctopusArmCase3D/run_tapered_arm_and_sphere_with_flow.py
  sopht/simulator/flow/flow_simulators_3d.py
Labels: prio:high, refactor

#97 (#61) feat: 3d flow simulator tests
  .coveragerc
  tests/test_simulator/test_flow/test_flow_simulators_3d.py
Labels: enhancement, prio:high

#100 update: cluster submit scripts for stampede2
  scripts/cluster/README.md
  scripts/cluster/submit.py
Labels: enhancement, prio:high
