Repository SophT-Team/SophT, pull requests merged in 2022-11, with the labels that each got.

#70 feat : initial attempt at dumping required files for rod visuaization…
  examples/3d_examples/OctopusArmCase3D/run_tapered_arm_and_sphere_with_flow.py
  sopht_simulator/utils/__init__.py
  sopht_simulator/utils/io_utils.py
Labels: enhancement, prio:high

#77 refactor IO test and add CosseratRodIO test
  tests/test_utils/test_io.py
  tests/test_utils/test_io_2d.py
  tests/test_utils/test_io_3d.py
Labels: enhancement, prio:high

#79 refactor: lid driven cavity to use interactor interface
  examples/2d_examples/LidDrivenCavityCase/lid_driven_cavity_case.py
  examples/2d_examples/LidDrivenCavityCase/lid_driven_cavity_grid.py
  sopht/simulator/immersed_body/cosserat_rod/cosserat_rod_flow_interaction.py
  sopht/simulator/immersed_body/immersed_body_flow_interaction.py
  sopht/simulator/immersed_body/rigid_body/__init__.py
  sopht/simulator/immersed_body/rigid_body/rigid_body_flow_interaction.py
  sopht/simulator/immersed_body/rigid_body/rigid_body_forcing_grids.py
Labels: prio:low, refactor

#80 feat: tests for open end 3d circular cylinder grid
  sopht/simulator/immersed_body/rigid_body/rigid_body_forcing_grids.py
  tests/test_simulator/test_immersed_body/rigid_body/test_rigid_body_forcing_grids.py
Labels: enhancement, prio:low
